config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'events#index'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :events
  # resources :charges
  get 'charges/:id', to: 'charges#new', as:'charges'
  post 'charges/:id', to: 'charges#create', as:'charges_pay'
  get 'messages/:id', to: 'messages#new', as: 'messages_send'
  post 'messages/:id', to: 'messages#create'
  get 'registered_messages/:id', to: 'registered_messages#new', as: 'registered_messages_send'
  post 'registered_messages/:id', to: 'registered_messages#create'
  get 'my_event', to: 'events#my_event'
  get 'show_details/:id', to: 'events#show_details', as: 'show_details'
  post 'show_interest', to: 'events#show_interest'
  get 'registered_events', to: 'events#registered_events'
  get 'event_requests', to: 'events#event_requests'
  get 'event_accept/:id', to: 'events#event_accept', as: 'event_accept'
  get 'event_reject/:id', to: 'events#event_reject', as: 'event_reject'
  get 'interested_users/:id', to: 'events#interested_users', as: 'interested_users'
  get 'registered_users/:id', to: 'events#registered_users', as: 'registered_users'
  post 'post_comment/:id', to: 'events#post_comment', as: 'post_comment'
  get 'registration_form/:id', to: 'events#registration_form', as: 'registration_form'
  post 'register/:id', to: 'events#register', as: 'register'
  get 'notifications', to: 'notifications#show_notifications', as: 'notification'
  get 'receipt/:id/', to: 'events#show_receipt', as: 'receipt'
  get 'all_users', to: 'users#all_users', as: 'all_users'
  get 'add_role_admin/:id', to: 'users#add_admin_role', as: 'add_role_admin'
  get 'remove_role_admin/:id', to: 'users#remove_admin_role', as: 'remove_role_admin'
end

app/models/event.rb
# frozen_string_literal: true

class Event < ApplicationRecord
  validates :title, :user_id, :time, :date, :description, presence: true
  validate :event_date_cannot_be_in_the_past?
  
  has_one :event_address, dependent: :destroy
  has_one_attached :image
  has_many :interests, dependent: :destroy
  has_many :registrations, dependent: :destroy
  has_many :interested_users, through: :interests, source: :user
  has_many :users, through: :registrations
  has_many :comments, dependent: :destroy
  has_many :messages
  belongs_to :user
  belongs_to :category

  scope :search1, ->(s) { Event.joins(:category).where('title LIKE ? OR description LIKE ? OR category_name LIKE ? ', "%#{s}%", "%#{s}%", "%#{s}%").where(status: 'accepted').order(created_at: :desc) }

  accepts_nested_attributes_for :event_address, allow_destroy: true, reject_if: :all_blank


  def event_date_cannot_be_in_the_past?
    if date.present? && date < Date.today
      errors.add(:date, "can't be in the past")
    end
  end

  def is_interested?(arg1, arg2)
    !Interest.where('event_id LIKE ? AND user_id LIKE ?', "%#{arg1}", "%#{arg2}").empty?
  end

  def is_my_event?(arg1, arg2)
    !Event.where('id LIKE ? AND user_id LIKE ?', "%#{arg1}", "%#{arg2}").empty?
  end

  def is_registered?(arg1, arg2)
    !Registration.where('event_id LIKE ? AND user_id LIKE ?', "%#{arg1}", "%#{arg2}").empty?
  end

  def self.delete_event
    temp = Event.where(date: Date.today)
    temp.destroy_all
  end 
end

app/controllers/events_controller.rb
# frozen_string_literal: true

class EventsController < ApplicationController
  before_action :find_event, only: %i[show edit update destroy event_accept event_reject interested_users registered_users show_details post_comment registration_form register show_receipt]
  
  def new
    @event = Event.new
    @address = EventAddress.new
  end

  def create
    @event = Event.new(event_params)
    @event.user_id = current_user.id
    if @event.save
      flash.now[:alert] = 'Event Posted'
      redirect_to event_path(@event.id)
    else
      flash[:notice] = 'Event not Posted'
      redirect_to new_event_path
    end
  end

  def index
    if params[:query].present?
      @events = Event.search1(params[:query])
      respond_to do |format|
        format.js
      end
    else
      @events = Event.order(created_at: :desc).where(status: 'accepted')
    end
  end

  def update
    if @event.update(event_params)
      flash[:notice] = 'Event Updated'
      redirect_to event_path(@event)
    else
      flash[:notice] = 'Event not Updated'
      render 'edit'
    end
  end

  def destroy
    if @event.user_id == current_user.id
      if @event.destroy
        flash[:notice] = 'Event Deleted'
      else
        flash[:notice] = 'Event not Deleted'
      end
    else
      flash[:notice] = 'You cannot Deleted this event!!'
    end
    redirect_to events_path
  end

  def my_event
    @events = Event.where(user_id: current_user.id)
    @user = current_user
  end

  def show_interest
    @interest = Interest.new
    @interest.user_id = current_user.id
    @interest.event_id = params[:format]
    redirect_to root_path if @interest.save
  end

  def registered_events
    @registered_events = current_user.events
  end

  def event_requests
    @event_requests = Event.where(status: 'pending')
  end

  def event_accept
    @event.status = 'accepted'
    if @event.save
      flash[:notice] = 'Event Accepted'
      redirect_to event_requests_path(@event), notice: 'test'
    else
      flash[:notice] = 'Event not Accepted'
      redirect_to event_requests_path(@event)
    end
  end

  def event_reject
    @event.status = 'rejected'
    if @event.save
      flash[:notice] = 'Event Rejected'
      redirect_to event_requests_path(@event)
    else
      flash[:notice] = 'Event not Rejected'
      redirect_to event_requests_path(@event)
    end
  end

  def interested_users
    @interested_users = @event.interested_users
  end

  def registered_users
    @registered_users = @event.users
  end

  def show_details
    @event_comments = @event.comments
  end

  def post_comment
    @comment = current_user.comments.new(comment_params)
    @comment.event_id = @event.id
    if @comment.save
      flash[:notice] = 'Comment Posted'
      redirect_to show_details_path(@event.id)
    else
      flash[:notice] = 'Comment not Posted! Something is wrong!!'
      redirect_to show_details_path(@event.id) 
    end
  end

  def registration_form; end

  def register
    @register = Registration.new(registration_params)
    @register.event_id = @event.id
    @register.user_id = current_user.id
    @register.total_amount = (@event.price * @register.quantity.to_i)
    @register.status = false
    if @register.save
      flash[:notice] = 'Registered'
      redirect_to charges_path(@event.id)
    else
      flash[:notice] = 'Not Registered'
      redirect_to  root_path
    end
  end

  def show_receipt
    @registration = Registration.find_by(event_id: @event.id, user_id: current_user.id)
    @user = current_user
    respond_to do |format|
      format.html
      format.pdf {
        render template: 'events/show_receipt.html.erb',
               pdf: 'temp',
               layout: 'pdf.html'
      }
    end
  end

  private
  def find_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:title, :description, :date, :time, :website, :user_id, :category_id, :status, :price, :size, :image, event_address_attributes: %i[address_line1 address_line2 area city pincode])
  end

  def comment_params
    params.require(:comment).permit(:comment, :user_id, :event_id, :image)
  end

  def registration_params
    params.require(:register).permit(:quantity, :user_id, :event_id)
  end
end

app/helpers/events_helper.rb
# frozen_string_literal: true

module EventsHelper
  def pending_notification
    @pending_notification = Notification.where(user_id: current_user.id, status: false).count
  end

  def is_status_true?(arg1)
    Registration.find_by(event_id: arg1.id , user_id: current_user.id).status
  end
  
  def can_respond_requests?
    !current_user.has_role? :user
  end
end

app/views/events/_form.html.erb
<% if @event.errors.any? %>
<ul>
	<% @event.errors.full_messages.each do |msg| %>
	<li> <%= msg %> </li>
	<% end %>
</ul>
<% end %>

<table>
	<%= form_with model: @event do |form|  %>

	<tr>
		<td><%= form.label :title %></td>
		<td><%= form.text_field :title %></td>
	</tr>
	<tr>
		<td><%= form.label :description %></td>
		<td><%= form.text_area :description %></td>
	</tr>
	<tr>
		<td><%= form.label :category %></td>

		<td>
			<%= form.select(:category_id, options_from_collection_for_select(Category.all, :id, :category_name), include_blank: 'Select Category') %>
		</td>
	</tr>
	<tr>
		<td><%= form.label :date %></td>
		<td><%= form.date_field :date , min: Date.today %></td>
	</tr>
	<tr>
		<td><%= form.label :time %></td>
		<td><%= form.time_field :time %></td>
	</tr>
	<tr>
		<td><%= form.label :image %></td>
		<td><%= form.file_field :image %></td>
	</tr>
	<tr>
		<td><%= form.label :price %></td>
		<td><%= form.text_field :price %></td>
	</tr>
	<tr>
		<td><%= form.label :size %></td>
		<td><%= form.text_field :size %></td>
	</tr>
	<ul>
		<%= form.fields_for :event_address, @address do |addresses_form| %>

		<tr>
			<td><%= addresses_form.label :address_line1 , 'Venue Address Line 1' %></td>
			<td><%= addresses_form.text_field :address_line1 %></td>
		</tr>
		<tr>
			<td><%= addresses_form.label :address_line2 , 'Venue Address Line 2' %></td>
			<td><%= addresses_form.text_field :address_line2 %></td>
		</tr>
		<tr>
			<td><%= addresses_form.label :area , 'Venue Area'%></td>
			<td><%= addresses_form.text_field :area %></td>
		</tr>
		<tr>
			<td><%= addresses_form.label :pincode %></td>
			<td><%= addresses_form.text_field :pincode %></td>
		</tr>
		<tr>
			<td><%= addresses_form.label :city %></td>
			<td><%= addresses_form.text_field :city %></td>
		</tr>

		<% end %>
	</ul>
	<tr>
		<td><%=form.submit 'Post Event'%></td>
	</tr>
	<% end %>
</table>

app/views/events/_results.html.erb
<table border = '0'>
  <% @events.each do |event| %>
  <h4>
    <strong><%= event.title %></strong>
  </h4>
  <p>
    Description: <%= event.description %>
  </p>
  <% if event.image != nil %>
  <div style = 'width:750px; height:auto'>
    <%= image_tag(event.image , style: 'width:100%') if event.image.present? %>
  </div>
  <% end %>
  <table>
    <tr>
      <td>
        <p>Interests: <%= event.interests.count %>&emsp;&emsp;</p>
      </td>
      <td>
        <p>Comments: <%= event.comments.count %></p>
      </td>
    </tr>
  </table>
  <% unless current_user.has_role? :user %>
  <p>
    <%= link_to 'Show Details', show_details_path(event.id) %>
    &emsp;&emsp;
    <%= link_to 'Edit Event', edit_event_path(event.id) %>
    &emsp;&emsp;
    <%= link_to 'Delete Event', event_path(event.id), method: :delete %>
  </p>
  <% else %>
  <table>
    <tr>
      <td>
        <%= form_tag(show_details_path(event.id), method: :get) do %>
        <button class = 'btn btn-dark' type = 'submit'>Show Details</button>&emsp;
        <% end %>
      </td>
      <% unless event.is_interested?(event.id, current_user.id) || event.is_my_event?(event.id, current_user.id) %>
      <td>
        <%= form_tag(show_interest_path(event.id), method: :post) do %>
        <button class = 'btn btn-dark' type = 'submit'>Show Interest</button>&emsp;
        <% end %>
      </td>
      <% else %>
      <td>
        <button class = 'btn btn-dark' type = 'submit' disabled>Interested</button>&emsp;
      </td>
      <% end %>
      <% unless event.is_registered?(event.id,current_user.id) || event.is_my_event?(event.id , current_user.id) %>
      <td>
        <%= form_tag(registration_form_path(event.id), method: :get) do %>
        <button class = 'btn btn-dark' type = 'submit'>Register</button>
        <% end %>
      </td>
      <% else %>
      <td>
        <button class = 'btn btn-dark' type = 'submit' disabled>Registered</button>&emsp;
      </td>
      <% end %>
    </tr>
  </table>
  <% end %> <br><br>
  <p>
    ----------------------------------------------------------------------------------------------------------------------------------------------
  </p>
  <% end %>
</table>

app/views/events/edit.html.erb
<h4>Edit Event</h4>
<% if can? :update, @event %>
<%= render 'form' %>
<% end %>

app/views/events/event_requests.html.erb
<% if can_respond_requests? %>
<h4>Event Requests</h4>

<% @event_requests.each do |event| %>

<p>
	Title: <%= event.title %>
</p>

<p>
	Description: <%= event.description %>
</p>
<div style='width:400px; height:auto'>
	<%= image_tag(event.image , style:'width:100%') if event.image.present? %>
</div>
<p>
	Date: <%= event.date.strftime("%d %b '%y") %>
</p>

<p>
	Time: <%= event.time.strftime('%l:%M %p Onwards') %>
</p>
<% if event.website != nil %>
<p>
	Website: <%= event.website %>
</p>
<% end %>
<%= link_to 'Show Details' , show_details_path(event.id) %>
<%= link_to 'Accept', event_accept_path(e) %>
<%= link_to 'Reject', event_reject_path(e) %>
<p>---------------------------------------------------</p>
<% end %>
<% else %>
<h4>You Can't access this Page </h4>
<% end %>

app/views/events/index.html.erb
<div class="container ">
  <div class="row">
    <div class="col">
    </div>
    <div class="col-9">
      <br>
      <% if current_user %>
      <h3><strong>All Upcoming Events</strong></h3>
      <%= form_tag(root_path, method: :get, remote: true) do %>
      <%= text_field_tag :query, params[:query] , :size => '40', placeholder: '  Search for an event by name or category' %>
      <button class="btn btn-dark" type='submit'>Search</button>
      <% end %>
      <br />
      <p>
        ----------------------------------------------------------------------------------------------------------------------------------------------
      </p>
      <div id="eventpost_table">
        <table border="0">
          <% @events.each do |event| %>
          <h4>
            <strong><%= event.title %></strong>
          </h4>
          <p>
            Description: <%= event.description %>
          </p>
          <% if event.image != nil %>
          <div style='width:750px; height:auto'>
            <%= image_tag(event.image , style:'width:100%') if event.image.present? %>
          </div>
          <% end %>
          <table>
            <tr>
              <td>
                <p>Interests: <%= event.interests.count %>&emsp;&emsp;</p>
              </td>
              <td>
                <p>Comments: <%= event.comments.count %></p>
              </td>
            </tr>
          </table>
          <% if can? :update, event %>
          <p>
            <%= link_to 'Show Details', show_details_path(event.id) %>
            &emsp;&emsp;
            <%= link_to 'Edit Event', edit_event_path(event.id) %>
            &emsp;&emsp;
            <%= link_to 'Delete Event', event_path(event.id), method: :delete %>
          </p>
          <% else %>
          <table>
            <tr>
              <td>
                <%= form_tag(show_details_path(event.id), method: :get) do %>
                <button class="btn btn-dark" type='submit'>Show Details</button>&emsp;
                <% end %>
              </td>
              <% unless event.is_interested?(event.id,current_user.id) || event.is_my_event?(event.id , current_user.id) %>
              <td>
                <%= form_tag(show_interest_path(event.id), method: :post) do %>
                <button class="btn btn-dark" type='submit'>Show Interest</button>&emsp;
                <% end %>
              </td>
              <% else %>
              <td> <button class="btn btn-dark" type='submit' disabled>Interested</button>&emsp; </td> <% end %>
              <% unless event.is_registered?(event.id,current_user.id) || event.is_my_event?(event.id , current_user.id) %> <td>
                <%= form_tag(registration_form_path(event.id), method: "get") do %> <button class="btn btn-dark"
                  type="submit">Register</button> <% end %> </td> <% else %> <td> <button class="btn btn-dark"
                  type='submit' disabled>Registered</button>&emsp; </td> <% end %>
            </tr>
          </table>
          <% end %> <br><br>
          <p>
            ----------------------------------------------------------------------------------------------------------------------------------------------
          </p>
          <% end %>
        </table>
      </div>
      <div id="search_result">
      </div>
      <% else %>
      <%= link_to 'sign in', new_user_session_path %>
      <%= link_to 'sign up', new_user_registration_path %>
      <% end %>
    </div>
    <div class="col">
    </div>
  </div>
</div>

app/views/events/index.js.erb
$("#eventpost_table").hide();
$("#search_result").html("<%= escape_javascript(render :partial => 'results') %>");

app/views/events/interested_users.html.erb
<style type="text/css">
	table,
	th,
	td {
		border: 1px solid black;
	}
</style>
<% if @event.is_my_event?(@event.id ,current_user.id) %>

<h4>Total Interested Users: <%= @event.interests.count %> </h4>
<%= link_to 'Send Mail to All Interested Users', messages_send_path(@event) %>
<table>
	<tr>
		<th>username</th>
		<th>email</th>
	</tr>
	<% @interested_users.each do |users| %>

	<p>
		<tr>
			<td><%= users.username %></td>
			<td><%= users.email %></td>
		</tr>
	</p>

	<% end %>
</table>
<% end %>

app/views/events/my_event.html.erb
<h4><strong>Personal Details</strong></h4>
<p>---------------------------------------------------</p>
Name : <%= @user.name %> <br>
Email : <%= @user.email %><br>
<%= link_to 'Edit Profile', edit_user_registration_path %>
<br>
<br>
<br>
<h4><strong>My Events</strong></h4>
<p>---------------------------------------------------</p>
<% @events.each do |event| %>
<p>
	Title: <%= event.title %>
</p>
<p>
	Description: <%= event.description %>
</p>
<div style="width:400px; height:auto">
	<%= image_tag(event.image , style:'width:100%') %>
</div>
<p>
	Date: <%= event.date.strftime("%d %b '%y") %>
</p>
<p>
	Time: <%= event.time.strftime('%l:%M %p Onwards') %>
</p>
<% if event.website != nil %>
<p>
	Website: <%= event.website %>
</p>
<% end %>
<p>
	Status: <%= event.status %>
</p>
<%= link_to 'Edit Event', edit_event_path(event.id) %><br>
<%= link_to 'Delete Event', event_path(event.id), method: :delete %><br>
<%= link_to 'Interested Users', interested_users_path(event.id) %><br>
<%= link_to 'Registered Users', registered_users_path(event.id) %>
	<p>---------------------------------------------------</p>
<% end %>

app/views/events/new.html.erb
<h4>Add Event</h4>
<%= render 'form' %>

app/views/events/registered_events.html.erb
<h4><strong>Registered Events</strong></h4>
<p>-------------------------------------------------------------------------------------</p>
<% @registered_events.each do |event| %>
<% if is_status_true?(event) %>
<h5>
	<strong>
		<%=event.title %>
	</strong>
</h5><br>
<% if event.image != nil %>
<div style="width:450px; height:auto">
	<%= image_tag(event.image , style:'width:100%') if event.image.present? %>
</div>
<% end %><br>
<table>
	<tr>
		<td><%= form_tag(show_details_path(event.id), method: :get) do %>
			<button class="btn btn-dark" type='submit'>Show Details</button>&emsp;
			<% end %>
		</td>
		<td><%= form_tag(receipt_path(event.id), method: :get) do %>
			<button class="btn btn-dark" type='submit'>Receipt</button>&emsp;
			<% end %>
		</td>
		<td>
			<%= link_to 'Download Receipt', receipt_path(event.id, :format => :pdf) %>
		</td>
	</tr>
</table>

<p>-----------------------------------------------------------------------------------</p>
<% end %>
<% end %>

app/views/events/registered_users.html.erb
<style type="text/css">
	table,
	th,
	td {
		border: 1px solid black;
	}
</style>
<% if @event.is_my_event?(@event.id ,current_user.id ) %>

<h4>Total Registered Users: <%= @event.registrations.count %> </h4>
<%= link_to 'Send Mail to All Interested Users', registered_messages_send_path(@event) %>
<table>
	<tr>
		<th>username</th>
		<th>email</th>
	</tr>
	<% @registered_users.each do |user| %>

	<p>
		<tr>
			<td><%= user.username %></td>
			<td><%= user.email %></td>
		</tr>
	</p>
	<% end %>
</table>

<% end %>

app/views/events/show.html.erb
<h1>Event</h1>
<p>
	Title: <%= @event.title %>
</p>
<p>
	Description: <%= @event.description %>
</p>
<div style = 'width:400px; height:auto'>
	<%= image_tag(@event.image , style:'width:100%') if @event.image.present? %>
</div>
<p>
	Date: <%= @event.date.strftime("%d %b '%y") %>
</p>
<p>
	Time: <%= @event.time.strftime('%l:%M %p Onwards') %>
</p>
<p>
	Address line 1:<%= @event.event_address.address_line1 %>
</p>
<p>
	Address line 2:<%= @event.event_address.address_line2 %>
</p>
<p>
	Area:<%= @event.event_address.area %>
</p>
<p>
	City:<%= @event.event_address.city %>
</p>
<% if @event.website != nil %>
	<p>
		Website: <%= @event.website %>
	</p>
<% end %>

app/views/events/show_details.html.erb
<br>
<h4>
	<strong>
		<%= @event.title %>
	</strong>
</h4>
<p>----------------------------------------------------------------------------</p>
<p>
	Description: <%= @event.description %>
</p>
<div style = 'width:400px; height:auto'>
	<%= image_tag(@event.image, style: 'width:100%') if @event.image.present? %>
</div>
<table>
	<tr>
		<p>
			<td>Date:</td>
			<td><%= @event.date.strftime("%d %b '%y") %></td>
		</p>
	</tr>
	<tr>
		<p>
			<td>Time:</td>
			<td><%= @event.time.strftime('%l:%M %p Onwards') %></td>
		</p>
	</tr>
	<tr>
		<p>
			<td>Address line 1:</td>
			<td><%= @event.event_address.address_line1 %></td>
		</p>
	</tr>
	<tr>
		<p>
			<td>Address line 2:</td>
			<td><%= @event.event_address.address_line2 %></td>
		</p>
	</tr>
	<tr>
		<p>
			<td>Area:</td>
			<td><%= @event.event_address.area %></td>
		</p>
	</tr>
	<tr>
		<p>
			<td>City:</td>
			<td><%= @event.event_address.city %></td>
		</p>
	</tr>
	<tr>
		<% if @event.website != nil %>
		<p>
			<td>Website:</td>
			<td><%= @event.website %></td>
		</p>
		<% end %>
	</tr>

	<% if can? :update, @event %>
	<table>
		<tr><br>
			<td><%= link_to 'Edit Event', edit_event_path(@event.id) %>&emsp;&emsp;</td>
			<td><%= link_to 'Delete Event', event_path(@event.id), method: :delete %></td>
		</tr>
	</table>
	<% else %>
	<table>
		<tr>
			<br>
			<% unless @event.is_interested?(@event.id,current_user.id) && @event.is_my_event?(@event.id , current_user.id) %>
			<td>
				<%= form_tag(show_interest_path(@event.id), method: :post) do %>
				<button class = 'btn btn-dark' type = 'submit'>Show Interest</button>&emsp;
				<% end %>
			</td>
			<% else %>
			<td>
				<button class = 'btn btn-dark' type = 'submit' disabled>Interested</button>
			</td>
			<% end %>
			<% unless @event.is_registered?(@event.id,current_user.id) && @event.is_my_event?(@event.id , current_user.id) %>
			<td>
				<%= form_tag(registration_form_path(@event.id), method: :get) do %>
				<button class = 'btn btn-dark' type = 'submit'>Register</button>
				<% end %>
			</td>
			<% else %>
			<td>
				<button class = 'btn btn-dark' type = 'submit' disabled>Registered</button>&emsp;
			</td>
			<% end %>
		</tr>
	</table>
	<% end %>
	<br>
	<h5><strong>Comments</strong></h5>
	<p>----------------------------------------------------------------------------</p>
	<% @event_comments.each do |comment| %>
	<table>
		<tr>
			<% u = User.find(comment.user_id) %>
			<td><strong><%= u.name %>:</strong></td>
			<td><%= comment.comment %></td>
			<td>
				<div style = 'width:200px; height:auto'>
					<%= image_tag(comment.image , style:'width:100%') if comment.image.present? %>
				</div>
			</td>
		</tr>
	</table>
	<br>
	<% end %>
	<p>----------------------------------------------------------------------------</p>

	<%= form_with scope: :comment, url: post_comment_path(@event.id) , method: :post do |f| %>
	<table>
		<tr>
			<td><%= f.label :comment %>:</td>
			<td><%= f.text_area :comment %></td>
			<td><%= f.file_field :image %></td>
		</tr>
	</table>
	<%=f.submit  class:'btn btn-dark' %>
	<% end %>

app/views/events/show_receipt.html.erb
<br>
<h4>
	<strong>
		<%= @event.title %>
	</strong>
</h4>
<p>-------------------------------------------------------------------------------------</p>
<% if @event.image != nil %>
<div style = 'width:450px; height:auto'>
	<%= image_tag(@event.image , style: 'width:100%') if @event.image.present? %>
</div>
<% end %>
<p>-------------------------------------------------------------------------------------</p>
<h5><strong>Payment Details:-</strong></h5>
<table>
	<tr>
		<td>
			Name:
		</td>
		<td>
			<%= @user.name %>
		</td>
	</tr>
	<tr>
		<td>
			Email
		</td>
		<td>
			<%= @user.email %>
		</td>
	</tr>
	<tr>
		<td>
			Quantity:
		</td>
		<td>
			<%= @registration.quantity %>
		</td>
	</tr>
	<tr>
		<td>
			Total amount:
		</td>
		<td>
			<%= @registration.total_amount %>
		</td>
	</tr>
</table>
<br>
<h5><strong>Event Details:-</strong></h5>
<table>
	<tr>
		<td>Date:</td>
		<td>
			<%= @event.date.strftime("%d %b '%y") %>
		</td>
	</tr>
	<tr>
		<td>Time:</td>
		<td>
			<%= @event.time.strftime('%l:%M %p Onwards') %>
		</td>
	</tr>
	<tr>
		<td>Venue:</td>
		<td>
			<%= @event.event_address.address_line1 %>,
		</td>
	</tr>
	<tr>
		<td></td>
		<td>
			<%= @event.event_address.address_line2 %>,
		</td>
	</tr>
	<tr>
		<td></td>
		<td>
			<%= @event.event_address.area %>,<%= @event.event_address.city %>.
		</td>
	</tr>
</table>