config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'events#index'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :events
  # resources :charges
  get 'charges/:id', to: 'charges#new', as:'charges'
  post 'charges/:id', to: 'charges#create', as:'charges_pay'
  get 'messages/:id', to: 'messages#new', as: 'messages_send'
  post 'messages/:id', to: 'messages#create'
  get 'registered_messages/:id', to: 'registered_messages#new', as: 'registered_messages_send'
  post 'registered_messages/:id', to: 'registered_messages#create'
  get 'my_event', to: 'events#my_event'
  get 'show_details/:id', to: 'events#show_details', as: 'show_details'
  post 'show_interest', to: 'events#show_interest'
  get 'registered_events', to: 'events#registered_events'
  get 'event_requests', to: 'events#event_requests'
  get 'event_accept/:id', to: 'events#event_accept', as: 'event_accept'
  get 'event_reject/:id', to: 'events#event_reject', as: 'event_reject'
  get 'interested_users/:id', to: 'events#interested_users', as: 'interested_users'
  get 'registered_users/:id', to: 'events#registered_users', as: 'registered_users'
  post 'post_comment/:id', to: 'events#post_comment', as: 'post_comment'
  get 'registration_form/:id', to: 'events#registration_form', as: 'registration_form'
  post 'register/:id', to: 'events#register', as: 'register'
  get 'notifications', to: 'notifications#show_notifications', as: 'notification'
  get 'receipt/:id/', to: 'events#show_receipt', as: 'receipt'
  get 'all_users', to: 'users#all_users', as: 'all_users'
  get 'add_role_admin/:id', to: 'users#add_admin_role', as: 'add_role_admin'
  get 'remove_role_admin/:id', to: 'users#remove_admin_role', as: 'remove_role_admin'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Eventhub</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>

  <% if current_user %>
  <nav class = 'navbar navbar-expand-lg navbar-dark bg-dark'>
    <% if current_user.has_role? :super_admin %>
    <a class = 'navbar-brand' href = '/'>
      <h3>Eventhub::Super-Admin Panel</h3>
    </a>
    <% elsif current_user.has_role? :admin %>
    <a class = 'navbar-brand' href = '/'>
      <h3>Eventhub::Admin Panel</h3>
    </a>
    <% else %>
    <a class = 'navbar-brand' href = '/'>
      <h3><strong>Eventhub</strong></h3>
    </a>
    <% end %>
    <button class = 'navbar-toggler' type = 'button' data-toggle = 'collapse' data-target = '#navbarNav'
      aria-controls = 'navbarNav' aria-expanded = 'false' aria-label = 'Toggle navigation'>
      <span class = 'navbar-toggler-icon'></span>
    </button>
    <div class = 'collapse navbar-collapse' id = 'navbarText'>
      <ul class = 'navbar-nav mr-auto'>
      </ul>
      <span class = 'navbar-text'>
        <ul class = 'navbar-nav'>
          <li class = 'nav-item'>
            <a class = 'nav-link active' href = '/'>Dashboard <span class = 'sr-only'>(current)</span></a>
          </li>
          <% if current_user.has_role? :super_admin %>
          <div class = 'nav-link'>
            <%= link_to 'All Users', all_users_path %>
          </div>
          <% end %>
          <li class = 'nav-item'>
            <a class = 'nav-link active' href = '/events/new'>Add Event</a>
          </li>
          <li class = 'nav-item'>
            <a class = 'nav-link active' href = '/my_event'>My Profile</a>
          </li>
          <% if current_user.has_role? :admin or current_user.has_role? :super_admin %>
          <div class = 'nav-link'>
            <%= link_to 'Event Requests', event_requests_path %>
          </div>
          <% else %>
          <div class = 'nav-link'>
            <%= link_to 'Registered Events', registered_events_path %>
          </div>
          <% end %>
          <% if current_user.has_role? :user %>
          <li class = 'nav-item'>
            <div class = 'nav-link'>
              <%= link_to "Notification(#{pending_notification})", notification_path  %>
            </div>
          </li>
          <% end %>
          <li class = 'nav-item'>
            <div class = 'nav-link'>
              <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
            </div>
          </li>
        </ul>
      </span>
    </div>
  </nav>
  <% end %>
  <%= yield %>
</body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/pdf.html.erb
# file: rails-generate-pdf/views/layotus/pdf.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>PDFs - Ruby on Rails</title>
    <!--     <%= wicked_pdf_stylesheet_link_tag "application" %>
 -->
</head>
<body>
    <%= yield %>
</body>
</html>